import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sip Finder App',
  description:
    'A cocktail searching app powered by The Cocktail DB Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {/* NAVBAR */}
          <div>{children}</div>
          {/* FOOTER */}
        </main>
      </body>
    </html>
  );
}
